#! /usr/bin/env bash

# Copyright © 2023, 2024, 2025, 2026 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

function usage() {
echo '
Show the extended status of multiple repositories and/or trees

git global-status [options]... [repo_path]...

Options:
    --origin    List by "origin" remote location
    --path      List by full repository/worktree path
    --repo      List by shortened repository path
    --worktree  List by shortened worktree path
    --no-ab     No ahead/behind
    --bare      Show repositories without any worktrees
    --status    Show status information
    --stash     Show existing stashes
    --upstream  Show commit counts relative to UPSTREAM_HEAD symbolic reference
'
}

declare -a dirs
declare -a repos
declare -a unique_repos
declare -a worktrees
opt_disppath='' # origin, path, git-dir, repo, worktree
opt_ab='true'
opt_bare='false'
opt_status='false'
opt_stash='false'
opt_upstream='false'
opt_untracked='true'
max_repo_length=0
max_repo_s_length=0
max_worktree_length=0
max_worktree_s_length=0
columns="$(tput cols)"

git_c_add="$(git config get --type=color --default=$'\e[32m' color.status.added)"
git_c_chg="$(git config get --type=color --default=$'\e[33m' color.status.changed)"
git_c_unt="$(git config get --type=color --default=$'\e[31m' color.status.untracked)"
git_c_local="$(git config get --type=color --default=$'\e[32m' color.branch.local)"
git_c_upstr="$(git config get --type=color --default=$'\e[34m' color.branch.upstream)"
git_c_workt="$(git config get --type=color --default=$'\e[36m' color.branch.worktree)"
git_c_plain="$(git config get --type=color --default=$'\e[1m' color.branch.plain)"

for opt in "$@"
do
	case "${opt}" in
		--origin)
			opt_disppath='origin'
		;;
		--path)
			opt_disppath='path'
		;;
		--repo)
			opt_disppath='repo'
		;;
		--worktree)
			opt_disppath='worktree'
		;;
		--no-ab)
			opt_ab='false'
		;;
		--bare)
			opt_bare='true'
		;;
		--status)
			opt_status='true'
		;;
		--stash)
			opt_stash='true'
		;;
		--upstream)
			opt_upstream='true'
		;;
		--no-untracked)
			opt_untracked='false'
		;;
		--help|-?)
			usage
			exit 0
		;;
		*)
			if   [[ -d "${opt}" ]]
			then
				# Standardize src_path
				dirs+=("$(realpath "${opt}")")
			else
				echo -e "\
\e[1;31mERROR: Unknown option or invalid path: ${opt}\e[0m

Use --help to see the available options"\
					> /dev/stderr
				exit 1
			fi
		;;
	esac
done

setup_tabs()
{
	local opt_disppath="${1}"
	local tgt_path="${2}"

	local extra_tabs='+8,+8,+8,+8,+8,+8,+8,+8,+8,+8,+8,+8,+8,+8,+8,+8,+8,+8,+8'

	case "${opt_disppath}" in
		origin)
			tabs $(( 8 < columns / 3 ? columns / 3 : 8 )),"${extra_tabs}"
		;;
		path)
			case "${tgt_path}" in
				repo)
					tabs $(( 5 < max_repo_length ? max_repo_length + 3 : 8 )),"${extra_tabs}"
				;;
				worktree)
					tabs $(( 5 < max_worktree_length ? max_worktree_length + 3 : 8 )),"${extra_tabs}"
				;;
			esac
		;;
		repo)
			tabs $(( 5 < max_repo_s_length ? max_repo_s_length + 3 : 8 )),"${extra_tabs}"
		;;
		worktree)
			tabs $(( 5 < max_worktree_s_length ? max_worktree_s_length + 3 : 8 )),"${extra_tabs}"
		;;
		*)
			echo "Invalid parameter at ${LINENO}" > /dev/stderr
			exit 1
		;;
	esac
}

process_worktree()
{
	repo_path="${1}"
	worktree="${2}"
	display="${3}"
	tgt_path="${4}"

	if   [[ -n "${worktree}" ]]
	then
		pushd "${worktree}" > /dev/null || exit 205
	else
		pushd "${repo_path}" > /dev/null || exit 205
	fi

	case "${display}" in
		origin)
			if   git remote | grep '^origin$' > /dev/null 2>&1
			then
				disppath="$(git remote get-url origin)"
			else
				repo_shortpath="${worktree#"${src_path}/"}"
				disppath="No \`origin\`; ${repo_shortpath:0:30}..."
			fi
			path_color="${git_c_upstr}"
		;;
		path)
			case ${tgt_path} in
				repo)
					disppath=${repo}
					path_color="${git_c_local}"
				;;
				worktree)
					disppath=${worktree}
					path_color="${git_c_workt}"
				;;
			esac
		;;
		repo)
			disppath="${repo_path#"${src_path}/"}"
			path_color="${git_c_local}"
		;;
		worktree)
			if   [[ -n "${worktree}" ]]
			then
				disppath="${worktree#"${src_path}/"}"
				path_color="${git_c_workt}"
			else
				disppath="${repo_path#"${src_path}/"}"
				path_color="${git_c_local}"
			fi
		;;
		*)
			echo "Invalid parameter at ${LINENO}" > /dev/stderr
			exit 1
		;;
	esac

	if   [[ -n "${worktree}" || 'true' == "${opt_bare}" ]]
	then
		# Display tree/repo path
		echo -ne "${path_color}${disppath}\e[0m"$'\t'
	fi

	if   [[ -n "${worktree}" ]]
	then
		ref="$(git branch --show-current)"

		if   [[ -n "${ref}" ]]
		then
			echo -ne "${git_c_local}${ref}\e[0m"

			if   [[ 'true' == "${opt_ab}" ]]
			then
				echo -ne ' is'

				ups_ref="$(git rev-parse --abbrev-ref -q --verify --end-of-options "${ref}"@\{upstream\})"
				if   [[ -n "${ups_ref}" ]]
				then
					ahead=$(git rev-list --count "${ups_ref}..${ref}")
					behind=$(git rev-list --count "${ref}..${ups_ref}")
					if   (( 0 < ahead + behind ))
					then
						if   (( 0 < ahead ))
						then
							echo -ne " \e[1;34m${ahead} ahead\e[0m"
						fi
						if   (( 0 < behind ))
						then
							echo -ne " \e[1;33m${behind} behind\e[0m"
						fi
					else
						echo -n ' up to date'
					fi
				else
					echo -n ' not tracking'
				fi
			fi

			if   [[ 'true' == "${opt_upstream}" ]]
			then
				if   git remote get-url upstream > /dev/null 2>&1
				then
					ups_ref="$(git rev-parse --abbrev-ref -q --verify --end-of-options UPSTREAM_HEAD)"
					if   [ -n "${ups_ref}" ]
					then
						behind=$(git rev-list --count "${ref}..${ups_ref}")
						if   (( 0 < behind ))
						then
							echo -ne ", \e[36m${behind} behind ${ups_ref}\e[0m"
						else
							echo -ne ", up to ${ups_ref}"
						fi
					else
						ups_ref="$(git rev-parse --abbrev-ref -q --verify --end-of-options refs/UPSTREAM_HEAD)"
						if   [[ -n "${ups_ref}" ]]
						then
							behind=$(git rev-list --count "${ref}..${ups_ref}")
							if   (( 0 < behind ))
							then
								echo -ne ", \e[36m${behind} behind ${ups_ref}\e[0m"
							else
								echo -ne ", up to ${ups_ref}"
							fi
						else
							echo -ne ', \e[1;31mno UPSTREAM_HEAD\e[0m'
						fi
					fi
				else
					echo -ne ', \e[1;34mno upstream\e[0m'
				fi
			fi
		else
			echo -ne "${git_c_plain}is detached\e[0m"
		fi

		if   [[ 'true' == "${opt_status}" ]]
		then
			if   [[ 'true' == "${opt_untracked}" ]]
			then
				status="$(git status --untracked-files=all --porcelain)"
			else
				status="$(git status --untracked-files=no --porcelain)"
			fi
			status_index="$(grep -G -c   '^[^ ][ ]'    <<< "${status}")"
			status_tree="$(grep -G -c    '^[ ][^ ]'   <<< "${status}")"
			status_both="$(grep -G -c '^[^ ?!][^ ?!]' <<< "${status}")"
			status_untr="$(grep -G -c      '^??'      <<< "${status}")"
			if   (( 0 < status_both + status_index + status_tree + status_untr ))
			then
				echo -n $';\ttree has'
				if   (( 0 < status_both ))
				then
					echo -ne " \e[36m${status_both} stage+mod\e[0m"
				fi
				if   (( 0 < status_index ))
				then
					echo -ne " ${git_c_add}${status_index} staged\e[0m"
				fi
				if   (( 0 < status_tree ))
				then
					echo -ne " ${git_c_chg}${status_tree} modified\e[0m"
				fi
				if   (( 0 < status_untr ))
				then
					echo -ne " ${git_c_unt}${status_untr} untracked\e[0m"
				fi
				echo -n ' files'
			fi
		fi

	elif [[ 'true' == "${opt_bare}" ]]
	then
		echo -n 'has no worktrees'
	fi

	if   [[ -n "${worktree}" || 'true' == "${opt_bare}" ]]
	then
		if   [[ 'true' == "${opt_stash}" ]]
		then
			if   git refs exists refs/stash 2>/dev/null
			then
				echo -ne ';\thas a stash'
			fi
		fi

		echo
	fi

	popd > /dev/null || exit 205
}

pushd . > /dev/null
for src_path in "${dirs[@]}"
do
	# BEGIN Find potential repos

	unique_repos=()
	repos=()
	worktrees=()

	echo -e "Looking for \e[1mrepos\e[0m in \e[94m${src_path}\e[0m ..."

	# Repos have an objects and refs subdirectories (the git-daemon repo check equivalent)
	tgt_path="$(find "${src_path}" -type d -name objects -print | sort)"

	for repo_test_refs in ${tgt_path}
	do
		# Set the potential repo path and reuse late
		repo_path="${repo_test_refs%/objects}"

		# Check for a sibling refs directory
		if   [[ -d "${repo_path}/refs" ]]
		then
			repo_shortpath="${repo_path#"${src_path}/"}"
			max_repo_length=$(( max_repo_length <= ${#repo_path} ? ${#repo_path} : max_repo_length ))
			max_repo_s_length=$(( max_repo_s_length <= ${#repo_shortpath} ? ${#repo_shortpath} : max_repo_s_length ))

			unique_repos+=("${repo_path}")

			# Look for worktrees in this repo
			worktree=''

			# Detached worktrees check
			if   [[ -d "${repo_path}/worktrees" ]]
			then
				for worktree_file in $(find "${repo_path}/worktrees" -type f -name gitdir -print | sort)
				do
					worktree_git="$(< "${worktree_file}")"
					worktree="${worktree_git%/.git}"

					repos+=("${repo_path}")
					worktrees+=("${worktree}")

					worktree_s="${worktree#"${src_path}/"}"
					max_worktree_length=$(( max_worktree_length <= ${#worktree} ? ${#worktree} : max_worktree_length ))
					max_worktree_s_length=$(( max_worktree_s_length <= ${#worktree_s} ? ${#worktree_s} : max_worktree_s_length ))
				done
			fi

			# "Main" worktree check
			if [[ "${repo_path}" == "${repo_path%/.git}/.git" ]]
			then
				worktree="${repo_path%/.git}"

				repos+=("${repo_path}")
				worktrees+=("${worktree}")

				worktree_s="${worktree#"${src_path}/"}"
				max_worktree_length=$(( max_worktree_length <= ${#worktree} ? ${#worktree} : max_worktree_length ))
				max_worktree_s_length=$(( max_worktree_s_length <= ${#worktree_s} ? ${#worktree_s} : max_worktree_s_length ))
			fi

			# When no worktrees are found
			if   [[ -z "${worktree}" ]]
			then
				repos+=("${repo_path}")
				worktrees+=('')
			fi
		fi
	done

	setup_tabs "${opt_disppath:-repo}" 'repo'

	for (( n = 0; n < ${#worktrees[@]}; n++ ))
	do
		process_worktree "${repos[n]}" "${worktrees[n]}" "${opt_disppath:-repo}" 'repo'
	done

	# END   Find potential repos

	# BEGIN Find potential detached worktrees

	repos=()
	worktrees=()

	echo -e "Looking for \e[1mdetached worktrees\e[0m in \e[94m${src_path}\e[0m ..."

	# Detached worktrees have a .git file, not directory
	trees_gitfile="$(find "${src_path}" -type f -name .git -print | sort)"

	for tree_gitfile in ${trees_gitfile}
	do
		worktree=${tree_gitfile%/.git}

		tree_pre_gitdir="$(< "${tree_gitfile}")"

		if   [[ "${tree_pre_gitdir}" =~ ^gitdir:[[:space:]] ]]
		then
			tree_gitdir="${tree_pre_gitdir#gitdir: }"

			if   [[ -d "${tree_gitdir}" ]]
			then
				repo_path="$(git -C "${tree_gitdir}" rev-parse --git-common-dir)"

				# Don't list the worktree if it has already been found by the repo search
				for test_repo in "${unique_repos[@]}"
				do
					if   [[ "${test_repo}" == "${repo_path}" ]]
					then
						repo_path=''
						break;
					fi
				done

				if   [[ -n "${repo_path}" ]]
				then
					repos+=("${repo_path}")
					worktrees+=("${worktree}")

					repo_shortpath="${repo_path#"${src_path}/"}"
					max_repo_length=$(( max_repo_length <= ${#repo_path} ? ${#repo_path} : max_repo_length ))
					max_repo_s_length=$(( max_repo_s_length <= ${#repo_shortpath} ? ${#repo_shortpath} : max_repo_s_length ))
					worktree_s="${worktree#"${src_path}/"}"
					max_worktree_length=$(( max_worktree_length <= ${#worktree} ? ${#worktree} : max_worktree_length ))
					max_worktree_s_length=$(( max_worktree_s_length <= ${#worktree_s} ? ${#worktree_s} : max_worktree_s_length ))
				fi
			else
				if [[ 'path' == "${opt_disppath:-worktree}" ]]
				then
					disppath=${worktree}
				else
					disppath=${worktree#"${src_path}/"}
				fi
				echo -e "\e[1;31mDetached tree\e[0m ${git_c_workt}${disppath}\e[0m \e[1;31mis invalid\e[0m"
			fi
		fi
	done

	setup_tabs "${opt_disppath:-worktree}" 'worktree'

	for (( n = 0; n < ${#worktrees[@]}; n++ ))
	do
		process_worktree "${repos[n]}" "${worktrees[n]}" "${opt_disppath:-worktree}" 'worktree'
	done

	# END   Find potential detached worktrees
done
popd > /dev/null || exit 205

# Restore TABS
tabs "${USER_TABS}"
