#! /usr/bin/env bash

# Copyright © 2025, 2026 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

dir="${1:-${USER_STORE_MIRROR_IMAGES:-.}}"

user_mirror_file="${XDG_CONFIG_DIR:-${HOME}/.config}/user_mirrors/openSUSE_Tumbleweed"
# shellcheck disable=SC2162
[[ -r "${user_mirror_file}" ]] && read user_mirror < "${user_mirror_file}"

mirror="${2:-${user_mirror:-https://download.opensuse.org}}"

dll="${mirror}/tumbleweed/iso/"

# shellcheck disable=SC2086
wget -r -l 1 -np -N -e robots=off \
	-P "${dir}/openSUSE/Tumbleweed" \
	-nd \
	--reject-regex 'C=|/Changes\.|-Current.iso|-aarch64-|-ppc64le-|-s390x-|-MicroOS-|-GNOME-|-XFCE-|-Rescue-' \
	-R '*.html' \
	-R '*.html.tmp' \
	-R '*.mirrorlist' \
	${dll}
