#! /usr/bin/env bash

# Copyright © 2025, 2026 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

for cmd in \
	curl \
	head \
	sed \
;
do
	if   ! which "${cmd}" > /dev/null 2>&1
	then
		echo -e "\e[1;31mERROR: ${cmd} command is not available\e[0m" > /dev/stderr
		exit 1
	fi
done

dir="${1:-${USER_STORE_MIRROR_IMAGES:-.}}"

dll="$(curl --silent 'https://sourceforge.net/projects/gparted/rss?path=/gparted-live-stable' | sed -n -E -e '/      <link>/{ /\/source\//{ d; b; }; s/(      |\/download)<[^<>]*>//gp }' | head -3)"

# shellcheck disable=SC2086
wget -N \
	-e 'dot_bytes = 4m' \
	-e 'dot_spacing = 8' \
	-e 'dots_in_line = 64' \
	-P "${dir}/GPartedLive" \
	${dll}
