#! /usr/bin/env bash

# Copyright © 2025, 2026 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

dir="${1:-${USER_STORE_MIRROR_IMAGES:-.}}"

user_mirror_file="${XDG_CONFIG_DIR:-${HOME}/.config}/user_mirrors/Fedora"
# shellcheck disable=SC2162
[[ -r "${user_mirror_file}" ]] && read user_mirror < "${user_mirror_file}"

mirror="${2:-${user_mirror:-https://download.fedoraproject.org/pub/fedora/linux}}"
mirror_pn=$(( $(tr -d -c '/' <<< "${mirror%/}" | wc -m) - 2 ))

dll=''
for ver in '42' '43'
do
	for dist in \
		'Everything' \
		'KDE' \
		'Server' \
	;
	do
		dll+=" ${mirror}/releases/${ver}/${dist}/"
	done
done

# shellcheck disable=SC2086
wget -r -l 3 -N -np -e robots=off \
	-P "${dir}/Fedora" \
	-nH --cut-dirs=$(( mirror_pn + 1 )) \
	--reject-regex 'C=|/aarch64/|/os/|/images/|/source/|/debug/' \
	-R '*.html' \
	-R '*.html.tmp' \
	-R '*.iso.manifest' \
	${dll}
