#! /usr/bin/env bash

# Copyright © 2025, 2026 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

for cmd in \
	curl \
	grep \
	htmlq \
;
do
	if   ! which "${cmd}" > /dev/null 2>&1
	then
		echo -e "\e[1;31mERROR: ${cmd} command is not available\e[0m" > /dev/stderr
		exit 1
	fi
done

dir="${1:-${USER_STORE_MIRROR_IMAGES:-.}}"

dll=$(curl --silent 'https://www.system-rescue.org/Download/' | htmlq --base 'https://www.system-rescue.org/Download/' --attribute href '#download-links + table td + td a' | grep -E -v '\.(iso\.asc|iso/download)')

# Legacy downloads
for ver in '11.02' '11.03'
do
	dll+=" https://www.system-rescue.org/releases/${ver}/systemrescue-${ver}-amd64.iso.sha256"
	dll+=" https://www.system-rescue.org/releases/${ver}/systemrescue-${ver}-amd64.iso.sha512"
	dll+=" https://sourceforge.net/projects/systemrescuecd/files/sysresccd-x86/${ver}/systemrescue-${ver}-amd64.iso"
done

# shellcheck disable=SC2086
wget -N \
	-P "${dir}/SystemRescue" \
	${dll}
