#! /usr/bin/env bash

# Copyright © 2025, 2026 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

dir="${1:-${USER_STORE_MIRROR_IMAGES:-.}}"

user_mirror_file="${XDG_CONFIG_DIR:-${HOME}/.config}/user_mirrors/KDE-Linux"
# shellcheck disable=SC2162
[[ -r "${user_mirror_file}" ]] && read user_mirror < "${user_mirror_file}"

mirror="${2:-${user_mirror:-https://files.kde.org/kde-linux}}"

yesterday="$(date --date='yesterday' +%Y%m%d)"
twodaysago="$(date --date='2 days ago' +%Y%m%d)"

wget -r -l 1 -np -N -e robots=off \
	-e 'dot_bytes = 16m' \
	-e 'dot_spacing = 8' \
	-e 'dots_in_line = 64' \
	-P "${dir}/KDE-Linux" \
	-nd \
	--reject-regex "C=|kdeos|sysupdate|kde-linux_${yesterday}|kde-linux_${twodaysago}" \
	-R '*.html' \
	-R '*.html.tmp' \
	-R '*.torrent' \
	"${mirror}/"

if   pushd "${dir}/KDE-Linux/" > /dev/null
then
	dll=''
	for file in \
		*.efi \
		*.erofs \
		*.erofs.caibx \
		*.raw \
		*.zst \
	;
	do
		chkfile="${file}.sha256"

		if   [[ ! -f "${chkfile}" ]]
		then
			dll+=" ${mirror}/${chkfile}"
		fi
	done

	if   [[ -n "${dll}" ]] && popd > /dev/null
	then
		# shellcheck disable=SC2086
		wget -N \
			-P "${dir}/KDE-Linux" \
			${dll}
	fi
fi
