#! /usr/bin/env bash

# Copyright © 2026 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

dir="${1:-${USER_STORE_MIRROR_PACKAGES:-.}}"
fulldir="${dir}/NVIDIA"

user_mirror_file="${XDG_CONFIG_DIR:-${HOME}/.config}/user_mirrors/NVIDIA_Linux"
# shellcheck disable=SC2162
[[ -r "${user_mirror_file}" ]] && read user_mirror < "${user_mirror_file}"

mirror="${2:-${user_mirror:-https://download.nvidia.com}}"

os_list='
	XFree86/Linux-x86_64
'
accept_regex='/580.142/?$|/580.142/'

dll=''
for os in ${os_list}
do
	dll+=" ${mirror}/${os}/"
done

wget -r -l 2 -np -N -e robots=off \
	-e 'dot_bytes = 4m' \
	-e 'dot_spacing = 8' \
	-e 'dots_in_line = 64' \
	-P "${fulldir}/" \
	-nH \
	--accept-regex "${accept_regex}" \
	--reject-regex '/README/?$' \
	-R '*.html' \
	-R '*.html.tmp' \
	${dll}

# Download the READMEs

dll=''
for os in ${os_list}
do
	dll+=" $(command ls -1d "${fulldir}/${os}"/*/ | command sed -e "s@^${fulldir}@${mirror}@;"' s@$@README/@')"
done

wget -r -l 1 -np -N -e robots=off \
	-e 'dot_bytes = 4k' \
	-e 'dot_spacing = 8' \
	-e 'dots_in_line = 64' \
	-P "${fulldir}/" \
	-nH \
	--accept-regex "${accept_regex}" \
	${dll}
