#! /usr/bin/env bash

# Copyright © 2025, 2026 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

dir="${1:-${USER_STORE_MIRROR_IMAGES:-.}}"

user_mirror_file="${XDG_CONFIG_DIR:-${HOME}/.config}/user_mirrors/Ubuntu_cdimage"
# shellcheck disable=SC2162
[[ -r "${user_mirror_file}" ]] && read user_mirror < "${user_mirror_file}"

mirror="${2:-${user_mirror:-https://cdimage.ubuntu.com}}"

for ver in '24.04' '26.04'
do
	for dist in \
		'Kubuntu/kubuntu' \
		'Lubuntu/lubuntu' \
		'Ubuntu-Budgie/ubuntu-budgie' \
		'Ubuntu-Cinnamon/ubuntucinnamon' \
		'Ubuntu-Mate/ubuntu-mate' \
		'Ubuntu-Studio/ubuntustudio' \
	;
	do
		wget -r -l 3 -np -N -e robots=off \
			-e 'dot_bytes = 16m' \
			-e 'dot_spacing = 8' \
			-e 'dots_in_line = 64' \
			-P "${dir}/${dist%/*}/${ver}" \
			-nd \
			--reject-regex 'C=|/snapshot[0-9]/|/snapshot-[0-9]/' \
			-R '*.html' \
			-R '*.html.tmp' \
			-R '*.list' \
			-R '*.manifest' \
			-R '*.iso.torrent' \
			-R '*.iso.zsync' \
			"${mirror}/${dist#*/}/releases/${ver}/release/"
	done
done
