#! /usr/bin/env bash

# Copyright © 2025 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

dir="${1:-.}"

user_mirror_file="${XDG_CONFIG_DIR:-${HOME}/.config}/user_mirrors/OPNsense"
# shellcheck disable=SC2162
[[ -r "${user_mirror_file}" ]] && read user_mirror < "${user_mirror_file}"

mirror="${2:-${user_mirror:-https://pkg.opnsense.org/releases/mirror}}"

wget -r -l 1 -np -N -e robots=off \
	-P "${dir}/OPNsense" \
	-nd \
	--reject-regex 'C=|-nano-|-serial-' \
	-R '*.html' \
	-R '*.html.tmp' \
	"${mirror}"
