#! /usr/bin/env bash

# Copyright © 2024 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

_git_histogram()
{
	__gitcomp '
		--author-order
		--committer-order
		--authors
		--committers
		--hour
		--weekday
		--week
		--month

		--all
		--branches
		--tags
		--no-merges
		--full-history
	'
}
