#! /usr/bin/env bash

# Copyright © 2024, 2025 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

_git_stagegui()
{
	case "${cur}" in
		# Options

		# git diff options
		--diff-algorithm=*)
			__gitcomp "${__git_diff_algorithms}" '' "${cur##--diff-algorithm=}"
			return
		;;
		--inter-hunk-context=*)
			__gitcomp '1 2 3 4 5 6 7 8 9' '' "${cur##--inter-hunk-context=}"
			return
		;;
		--unified=*)
			__gitcomp '1 2 3 4 5 6 7 8 9' '' "${cur##--unified=}"
			return
		;;
		*)
			__gitcomp '
				--dense
				--sparse

				--diff-algorithm=
				--inter-hunk-context=
				--unified=
			'
			return
		;;
	esac
}
