#! /usr/bin/env bash

# Copyright © 2024 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

_git_chrono()
{
	case "${cur}" in
		# Options
		--*)
			__gitcomp '
				--linear-days
				--linear-weeks
				--linear-months
				--linear-years
				--quadratic-days
				--quadratic-weeks
				--quadratic-months
				--quadratic-years
			'
			return
		;;
		*)
			__git_complete_index_file
		;;
	esac

	__git_complete_index_file
}
