#! /usr/bin/env bash

# Copyright © 2025, 2026 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

_comp_cmd_labhub()
{
	local curr prev command

	curr="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"

	local -a commands=(
		emojis
		gitignores
		info
		licenses
		releases
		release
		size
		stars
		tags
		tag
	)

	local -a global_opt=(
		-h --help
		--url
	)

	# Inside a git repo?
	git rev-parse --git-dir > '/dev/null' 2>&1
	if   (( 0 == $? ))
	then
		local remotes="$(command git remote)"

		if   [[ -n "${remotes}" ]]
		then
			global_opt+=( --remote )
		fi

		if   command grep '^upstream$' <<<"${remotes}" > '/dev/null' 2>&1
		then
			global_opt+=( --upstream )
		fi
	fi

	for (( i=0 ; i < COMP_CWORD ; i++ ))
	do
		if   [[ "-${COMP_WORDS[i]#-}" == "${COMP_WORDS[i]}" ]]
		then
			i+=1
			continue
		elif [[ " ${commands[*]} " =~ " ${COMP_WORDS[i]} " ]]
		then
			command="${COMP_WORDS[i]}"
			break;
		fi
	done

	case "${command}" in
		'' )
			case "${prev}" in
				-h | --help | --url )
					return
				;;
				--remote )
					COMPREPLY=( $(compgen -W "${remotes}" -- "${COMP_WORDS[COMP_CWORD]}") )
					return
				;;
				* )
					compopt -o nosort
					COMPREPLY=( $(compgen -W "${global_opt[*]} ${commands[*]}" -- "${COMP_WORDS[COMP_CWORD]}") )
					return
				;;
			esac
		;;
		size | stars )
			return
		;;
		emojis | gitignores | info | licenses | releases | release | tags | tag )
			COMPREPLY=( $(compgen -W "-h --help --json" -- "${COMP_WORDS[COMP_CWORD]}") )
			return
		;;
		* )
			return
		;;
	esac
} && complete -F _comp_cmd_labhub labhub
