#! /usr/bin/env bash

# Copyright © 2026 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

_comp_cmd_mkuserdirs()
{
	COMPREPLY=( $(compgen -W "$(mkuserdirs --bash-completion)" -- "${COMP_WORDS[COMP_CWORD]}") )
	return 0
} && complete -F _comp_cmd_mkuserdirs mkuserdirs
