#! /usr/bin/env bash

# Copyright © 2024, 2025 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

#
# Simple completions
#

# Commands
complete -c \
	which-bat \
	which-cat \
	which-file \
	which-ll \
	which-rpm \
	which-rpm-else \

# Usernames
complete -u \
	id-multiline \
