#! /usr/bin/env bash

# Copyright © 2025, 2026 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

cpupower "$@" \
| sed -E -e $'
	s/[0-9.]+ ?[MG]Hz/\e[1m&\e[0m/g
'
