#! /bin/sh

# Copyright © 2022, 2024, 2025 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

# Works up to a depth of 12 indentations

usage() {
echo '
Convert tabs to spaces or vice-versa

filter-indent <option>

Options:
    --1sp-to-tab
    --2sp-to-tab
    --4sp-to-tab
    --8sp-to-tab
    --tab-to-1sp
    --tab-to-2sp
    --tab-to-4sp
    --tab-to-8sp
    --help
    -?
'
}

case "$1" in
	--1sp-to-tab)
		sed -e '
s/^            /\t\t\t\t\t\t\t\t\t\t\t\t/
s/^           /\t\t\t\t\t\t\t\t\t\t\t/
s/^          /\t\t\t\t\t\t\t\t\t\t/
s/^         /\t\t\t\t\t\t\t\t\t/
s/^        /\t\t\t\t\t\t\t\t/
s/^       /\t\t\t\t\t\t\t/
s/^      /\t\t\t\t\t\t/
s/^     /\t\t\t\t\t/
s/^    /\t\t\t\t/
s/^   /\t\t\t/
s/^  /\t\t/
s/^ /\t/
' < /dev/stdin
	;;
	--2sp-to-tab)
		sed -e '
s/^                        /\t\t\t\t\t\t\t\t\t\t\t\t/
s/^                      /\t\t\t\t\t\t\t\t\t\t\t/
s/^                    /\t\t\t\t\t\t\t\t\t\t/
s/^                  /\t\t\t\t\t\t\t\t\t/
s/^                /\t\t\t\t\t\t\t\t/
s/^              /\t\t\t\t\t\t\t/
s/^            /\t\t\t\t\t\t/
s/^          /\t\t\t\t\t/
s/^        /\t\t\t\t/
s/^      /\t\t\t/
s/^    /\t\t/
s/^  /\t/
' < /dev/stdin
	;;
	--4sp-to-tab)
		sed -e '
s/^                                                /\t\t\t\t\t\t\t\t\t\t\t\t/
s/^                                            /\t\t\t\t\t\t\t\t\t\t\t/
s/^                                        /\t\t\t\t\t\t\t\t\t\t/
s/^                                    /\t\t\t\t\t\t\t\t\t/
s/^                                /\t\t\t\t\t\t\t\t/
s/^                            /\t\t\t\t\t\t\t/
s/^                        /\t\t\t\t\t\t/
s/^                    /\t\t\t\t\t/
s/^                /\t\t\t\t/
s/^            /\t\t\t/
s/^        /\t\t/
s/^    /\t/
' < /dev/stdin
	;;
	--8sp-to-tab)
		sed -e '
s/^                                                                                                /\t\t\t\t\t\t\t\t\t\t\t\t/
s/^                                                                                        /\t\t\t\t\t\t\t\t\t\t\t/
s/^                                                                                /\t\t\t\t\t\t\t\t\t\t/
s/^                                                                        /\t\t\t\t\t\t\t\t\t/
s/^                                                                /\t\t\t\t\t\t\t\t/
s/^                                                        /\t\t\t\t\t\t\t/
s/^                                                /\t\t\t\t\t\t/
s/^                                        /\t\t\t\t\t/
s/^                                /\t\t\t\t/
s/^                        /\t\t\t/
s/^                /\t\t/
s/^        /\t/
' < /dev/stdin
	;;
	--tab-to-1sp)
		sed -e '
s/^\t\t\t\t\t\t\t\t\t\t\t\t/            /
s/^\t\t\t\t\t\t\t\t\t\t\t/           /
s/^\t\t\t\t\t\t\t\t\t\t/          /
s/^\t\t\t\t\t\t\t\t\t/         /
s/^\t\t\t\t\t\t\t\t/        /
s/^\t\t\t\t\t\t\t/       /
s/^\t\t\t\t\t\t/      /
s/^\t\t\t\t\t/     /
s/^\t\t\t\t/    /
s/^\t\t\t/   /
s/^\t\t/  /
s/^\t/ /
' < /dev/stdin
	;;
	--tab-to-2sp)
		sed -e '
s/^\t\t\t\t\t\t\t\t\t\t\t\t/                        /
s/^\t\t\t\t\t\t\t\t\t\t\t/                      /
s/^\t\t\t\t\t\t\t\t\t\t/                    /
s/^\t\t\t\t\t\t\t\t\t/                  /
s/^\t\t\t\t\t\t\t\t/                /
s/^\t\t\t\t\t\t\t/              /
s/^\t\t\t\t\t\t/            /
s/^\t\t\t\t\t/          /
s/^\t\t\t\t/        /
s/^\t\t\t/      /
s/^\t\t/    /
s/^\t/  /
' < /dev/stdin
	;;
	--tab-to-4sp)
		sed -e '
s/^\t\t\t\t\t\t\t\t\t\t\t\t/                                                /
s/^\t\t\t\t\t\t\t\t\t\t\t/                                            /
s/^\t\t\t\t\t\t\t\t\t\t/                                        /
s/^\t\t\t\t\t\t\t\t\t/                                    /
s/^\t\t\t\t\t\t\t\t/                                /
s/^\t\t\t\t\t\t\t/                            /
s/^\t\t\t\t\t\t/                        /
s/^\t\t\t\t\t/                    /
s/^\t\t\t\t/                /
s/^\t\t\t/            /
s/^\t\t/        /
s/^\t/    /
' < /dev/stdin
	;;
	--tab-to-8sp)
		sed -e '
s/^\t\t\t\t\t\t\t\t\t\t\t\t/                                                                                                /
s/^\t\t\t\t\t\t\t\t\t\t\t/                                                                                        /
s/^\t\t\t\t\t\t\t\t\t\t/                                                                                /
s/^\t\t\t\t\t\t\t\t\t/                                                                        /
s/^\t\t\t\t\t\t\t\t/                                                                /
s/^\t\t\t\t\t\t\t/                                                        /
s/^\t\t\t\t\t\t/                                                /
s/^\t\t\t\t\t/                                        /
s/^\t\t\t\t/                                /
s/^\t\t\t/                        /
s/^\t\t/                /
s/^\t/        /
' < /dev/stdin
	;;
	--help|-?)
		usage
		exit 0
	;;
	*)
		cat < /dev/stdin
	;;
esac
