#! /bin/sh

# Copyright © 2022 Boian Berberov
# Licensed under the EUPL-1.2 only.
#
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

id "$@" | sed -e 's/ /\n/g; s/,\([0-9]\)/\n\t\1/g; s/groups=/groups:\n\t/'
