#! /bin/sh

# Copyright © 2025 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

lsusb "$@" \
| sed -E -e $'
	# List
	s/^Bus ([0-9a-f]{3}) Device ([0-9a-f]{3}): ID ([0-9a-f]{4}:[0-9a-f]{4})/\e[90mBus\e[0m \\1 \e[90mDevice\e[0m \\2\e[90m:\e[0m \e[90mID\e[0m \e[1m\\3\e[0m/

	# Verbose
	/^Negotiated speed: /{
		# Highlight values
		s/: /: \e[1m/
		s/$/\e[0m/

		# Header
		s/Negotiated speed:/\e[90mNegotiated speed:\e[0m/
	}

	/^Device Descriptor:/{ s/^/\e[90m/; s/$/\e[0m/; }
	/^  Configuration Descriptor:/{ s/^/\e[90m/; s/$/\e[0m/; }
	/^    Interface Descriptor:/{ s/^/\e[90m/; s/$/\e[0m/; }
	/^    Interface Association:/{ s/^/\e[90m/; s/$/\e[0m/; }
	s/^      ([[:alpha:]]+) Interface Descriptor:/\e[90m      \e[36m\\1\e[90m Interface Descriptor:\e[0m/
	/^      Endpoint Descriptor:/{ s/^/\e[90m/; s/$/\e[0m/; }

	/^  (idVendor|idProduct)/{
		s/^(.{23})/\\1\e[1m/;
		s/$/\e[0m/;
	}
	/^  (iManufacturer|iProduct|iSerial)/{
		s/^(.{28})/\\1\e[1m/;
		s/$/\e[0m/;
	}

	/Warning: /{ s/^/\e[1;33m/; s/$/\e[0m/; }

	/UNRECOGNIZED: /{ s/^/\e[1;31m/; s/$/\e[0m/; }
	/\*\* UNAVAILABLE \*\*/{ s/^/\e[1;31m/; s/$/\e[0m/; }

	# Tree
	/\/:  /{
		2,$i

		s/\/:  Bus ([0-9a-f]{3})\.Port ([0-9a-f]{3}): Dev ([0-9a-f]{3}),/\e[90m:__ \/ Bus \e[0m\\1\e[90m.Port \e[0m\\2\e[90m: Dev \e[0m\\3\e[90m,/

		s/Class=([^,]+),/Class=\e[0m\\1\e[90m,/
		s/Driver=([^,]+),/Driver=\e[0;1m\\1\e[0;90m,/
		s/([[:graph:]]+)$/\e[35m\\1\e[0m/
	}

	/    [ ]*ID/{
		s/ID ([0-9a-f]{4}:[0-9a-f]{4})/\e[90m\\\\ ID \e[0;1m\\1\e[0m/
	}

	/    [ ]*\|__/{
		i

		s/\|__ Port ([0-9a-f]{3}): Dev ([0-9a-f]{3}), If ([0-9a-f]+),/\e[90m|__ \/ Port \e[0m\\1\e[90m: Dev \e[0m\\2\e[90m, If \e[0m\\3\e[90m,/

		s/Class=([^,]+),/Class=\e[0m\\1\e[90m,/
		s/Driver=([^,]+),/Driver=\e[0;1m\\1\e[0;90m,/
		s/([[:graph:]]+)$/\e[35m\\1\e[0m/
	}
'
