#! /usr/bin/env bash

# Copyright © 2025, 2026 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

for name in "$@"
do
	echo "=== ${name} ==="
	echo --whatenhances
	rpm -q --whatenhances "${name}"
	echo
	echo --whatprovides
	rpm -q --whatprovides "${name}"
	echo
	echo --whatrecommends
	rpm -q --whatrecommends "${name}"
	echo
	echo --whatrequires
	rpm -q --whatrequires "${name}"
	echo
	echo --whatsuggests
	rpm -q --whatsuggests "${name}"
	echo
	echo --whatsupplements
	rpm -q --whatsupplements "${name}"
done \
| sed -e $'
	s/^=== .*/\e[1m&\e[0m/
	s/^--.*/\e[36m&\e[0m/
	s/^no package .*/\e[31m&\e[0m/
	s/^patterns-.*/\e[33m&\e[0m/
'
