#! /bin/sh

# Copyright © 2025 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

for name in "$@"
do
	echo "=== ${name} ==="
	echo --enhances
	rpm -q --enhances "${name}"
	echo --provides
	rpm -q --provides "${name}"
	echo --recommends
	rpm -q --recommends "${name}"
	echo --requires
	rpm -q --requires "${name}"
	echo --suggests
	rpm -q --suggests "${name}"
	echo --supplements
	rpm -q --supplements "${name}"
done \
| sed -e $'
	s/^--.*/\e[90m&\e[0m/
	s/^no package .*/\e[31m&\e[0m/
'
