#! /bin/sh

# Copyright © 2025 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

set -o noclobber
set -o errexit

uncrustify -c '-' --update-config          > "uncrustify.defaults.cfg"
uncrustify -c '-' --update-config-with-doc > "uncrustify.document.cfg"
