#! /bin/sh

# Copyright © 2023 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

for name in "$@"
do
	if [ -a "${name}" ]
	then
		rpm -qf "${name}"
	elif filepath=`which "${name}" 2>/dev/null`
	then
		rpm -qf "${filepath}"
	else
		echo "${name} not found"
	fi
done
