#! /bin/sh

# Copyright © 2023, 2024, 2025, 2026 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

for name in "$@"
do
	if   [ -e "${name}" ]
	then
		if   [ 1 -lt $# ]
		then
			printf '%s:\t' "${name}"
		fi

		rpm -qf "${name}"
	elif filepath=$(which "${name}" 2>/dev/null)
	then
		if   [ 1 -lt $# ]
		then
			printf '%s:\t' "${filepath}"
		fi

		rpm -qf "${filepath}"
	elif [ -e "/sbin/${name}" ]
	then
		if   [ 1 -lt $# ]
		then
			printf '%s:\t' "/sbin/${name}"
		fi

		rpm -qf "/sbin/${name}"
	elif [ -e "/usr/sbin/${name}" ]
	then
		if   [ 1 -lt $# ]
		then
			printf '%s:\t' "/usr/sbin/${name}"
		fi

		rpm -qf "/usr/sbin/${name}"
	else
		echo "${name} not found" > /dev/stderr
	fi
done
