#! /bin/sh

# Copyright © 2024 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

for name in "$@"
do
	if [ -a "${name}" ]
	then
		file "${name}"
	elif filepath=`which "${name}" 2>/dev/null`
	then
		ls --color=auto -lhd "${filepath}"
	else
		echo "${name} not found"
	fi
done
