#! /bin/sh

# Copyright © 2024, 2025, 2026 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

for name in "$@"
do
	if   [ -e "${name}" ]
	then
		bat "${name}"
	elif filepath=$(which "${name}" 2>/dev/null)
	then
		bat "${filepath}"
	elif [ -e "/sbin/${name}" ]
	then
		bat "/sbin/${name}"
	elif [ -e "/usr/sbin/${name}" ]
	then
		bat "/usr/sbin/${name}"
	else
		echo "${name} not found" > /dev/stderr
	fi
done
