#! /bin/sh

# Copyright © 2025 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

zypper --no-refresh info \
	--conflicts \
	--enhances \
	--obsoletes \
	--provides \
	--recommends \
	--requires \
	--suggests \
	--supplements \
	"$@" \
| sed -E -e $'
	s/^-----------------------[-]*/\e[90m&\e[0m/

	/^Name           :/{
		s/: /:/
		s/[^:]+$/ \e[1m&\e[0m/
	}

	/^Version        :/{
		s/: ([^-]+)(-?)(.*)/: \e[32m\\1\e[0m\\2\e[36m\\3\e[0m/
	}

# 	/^Installed Size :/{
# 	}

	/^Installed      :/{
		s/No/\e[31m&\e[0m/
		s/Yes/\e[32m&\e[0m/
		s/automatically/\e[33m&\e[0m/
	}

	/^Status         :/{
		s/up-to-date/\e[32m&\e[0m/
	}

	/^Summary        :/{
		s/: /:/
		s/[^:]+$/ \e[1m&\e[0m/
	}

	/^Description    :/{
		a
	}

	/^(Provides   |Requires   |Conflicts  |Obsoletes  |Recommends |Suggests   |Supplements|Enhances   )    :/{
		/: ---/d

		i

		/: [^-[]/{
			s/\: /: [1]\\n    /
			P
			D
		}

	}
	/^(Provides   |Requires   |Conflicts  |Obsoletes  |Recommends |Suggests   |Supplements|Enhances   )    :/,${
		/^    \//{
			s@/(bin|usr/bin)@\e[34m&\e[0m@
			s@[^/ ]+$@\e[32m&\e[0m@
		}
		/\.so/{
			s/[^ ]+\.so[^(]*/\e[36m&\e[0m/
		}

		/^    (appdata|application|metainfo|product)\(/{
			s/(appdata|application|metainfo|product)/\e[35m&\e[0m/
		}

		/^    (pattern|pattern-category|pattern-icon|pattern-order|pattern-visible)\(\)/{
			s/(pattern|pattern-category|pattern-icon|pattern-order|pattern-visible)/\e[35m&\e[0m/
			s/(=|==|<|>|<=|>=) (.+)/\e[1m\\1\e[0m \e[1m\\2\e[0m/
		}


		/^    (mimehandler|service|user)\(/{
			s/(mimehandler|service|user)/\e[33m&\e[0m/
		}

		/^    [[:alpha:]]/{
			s/[-[:alnum:]_+]+/\e[31m&\e[0m/
			s/-devel\e/\e[2m&/
			s/(=|==|<|>|<=|>=) ([^-]+)(-?)(.*)/\e[1m\\1\e[0m \e[32m\\2\e[0m\\3\e[36m\\4\e[0m/
		}
		/^    \(/{
			s/ \(/ ( /g
			s/\)\)\)\)/) ) ) )/g
			s/\)\)\)/) ) )/g
			s/\)\)/) )/g

			s@ (/(bin|usr/bin))@ \e[34m\\1\e[0m@
			s@/([^/ ]+) @/\e[32m\\1\e[0m @

			s/ ([^ ]+\.so[^(]*)/ \e[36m\\1\e[0m/

			s/ (appdata|application|metainfo|product)/ \e[35m\\1\e[0m/g

			s/ (pattern|pattern-category|pattern-icon|pattern-order|pattern-visible)/ \e[35m\\1\e[0m/g

			s/ (mimehandler|service|user)/ \e[33m\\1\e[0m/g

			s/ (\()/ \e[1m\\1\e[0m/g
			s/ (\))/ \e[1m\\1\e[0m/g
			s/ (if|or|and|=|==|<|>|<=|>=) / \e[1m\\1\e[0m /g

			s/ ([-[:alnum:]_+]+)/ \e[31m\\1\e[0m/
			s/-devel\e/\e[2m&/
		}
	}

'
