.\" Manpage for zypper-lifecycle.
.TH man 1 "2026-02-02" "" "zypper packages-color man page"
.SH NAME
zypper-packages-color \- highlighted package lists
.SH SYNOPSIS
.B zypper packages-color
.SH DESCRIPTION
.B zypper packages-color
show package lists with color highlights
.SH OPTIONS
The options are the same as those of
.B zypper packages
.SH BUGS
Maybe
.SH AUTHOR
Boian Berberov
.SH SEE ALSO
.BR zypper (8)
