.\" Manpage for zypper-lifecycle.
.TH man 1 "2026-02-02" "" "zypper info-color man page"
.SH NAME
zypper-info-color \- highlighted package information
.SH SYNOPSIS
.B zypper info-color
.SH DESCRIPTION
.B zypper info-color
show package information with color highlights
.SH OPTIONS
The options are the same as those of
.B zypper info
.SH BUGS
Maybe
.SH AUTHOR
Boian Berberov
.SH SEE ALSO
.BR zypper (8)
