.\" Manpage for zypper-lifecycle.
.TH man 1 "2026-02-02" "" "zypper search-color man page"
.SH NAME
zypper-search-color \- highlighted search results
.SH SYNOPSIS
.B zypper search-color
.SH DESCRIPTION
.B zypper search-color
show search results with color highlights
.SH OPTIONS
The options are the same as those of
.B zypper search
.SH BUGS
Maybe
.SH AUTHOR
Boian Berberov
.SH SEE ALSO
.BR zypper (8)
