#! /usr/bin/env bash

# Copyright © 2022, 2024, 2025 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

if   [[ "$(adb get-state)" != 'device' ]]
then
	echo -e '\e[1;31mERROR: Default Android device is not available\e[0m' > /dev/stderr
	exit 1
fi

sdk="$(adb shell 'getprop ro.build.version.sdk' | tr -d '\r')"

if   (( sdk < 23 ))
then
	echo -e '\e[1;31mERROR: Modern AppOps is not available before Android 6.0\e[0m' > /dev/stderr
	exit 1
fi

echo 'AppOps:'
if   (( sdk < 28 ))
then
	adb shell 'dumpsys appops' \
	| grep ': mode=' \
	| tr -d -c 'A-Z_\n' \
	| sed -e 's/^/\t- /' \
	| LC_ALL=C sort \
	| uniq
else
	adb shell 'dumpsys appops' \
	| grep -E ' Op [A-Z]|: mode=|\(allow|\(default|\(deny|\(ignore' \
	| sed -e 's/ Op //; /allow/s/(.*//' \
	| tr -d -c 'A-Z_\n' \
	| sed -e 's/^/\t- /' \
	| LC_ALL=C sort \
	| uniq
fi
