#! /usr/bin/env bash

# Copyright © 2022, 2024, 2025 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

if   [[ "`adb get-state`" != 'device' ]]
then
	echo -e '\e[1;31mERROR: Default Android device is not available\e[0m' > /dev/stderr
	exit 1
fi

adb shell 'getprop' \
| sed -e '
	s/\r//g
	s/^\[//
	s/\]: \[/: /
	s/\]$//
' \
| LC_ALL=C sort
