#! /bin/bash

# Copyright © 2022 Boian Berberov
# Licensed under the EUPL-1.2 only.
#
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

if   [[ "`adb get-state`" != 'device' ]]
then
	echo "ERROR: Default Android device is not available" > /dev/stderr
	exit 1
fi

sdk="`adb shell 'getprop ro.build.version.sdk' | tr -d '\r'`"

if   (( "${sdk}" < 23 ))
then
	echo "INFO: Cannot list settings on Android 5.1 and older devices"
	exit 0
fi

echo "System:"
adb shell "settings list system" | sed -e 's/\r//g; s/^/\t/; s/=/: /' | sort
echo "Secure:"
adb shell "settings list secure" | sed -e 's/\r//g; s/^/\t/; s/=/: /' | sort
echo "Global:"
adb shell "settings list global" | sed -e 's/\r//g; s/^/\t/; s/=/: /' | sort
