#! /usr/bin/env bash

# Copyright © 2022 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

if   [[ "`adb get-state`" != 'device' ]]
then
	echo "ERROR: Default Android device is not available" > /dev/stderr
	exit 1
fi

sdk="`adb shell 'getprop ro.build.version.sdk' | tr -d '\r'`"

if   (( "${sdk}" < 24 ))
then
	echo "ERROR: This operation is not available before Android 7.0.  Try adb-dump-appops." > /dev/stderr
	exit 1
fi

echo 'Allow:'
adb shell "appops query-op $1 allow" \
| tr -d '\r' \
| sort \
| sed -e 's/^/\t- /'

echo 'Ignore:'
adb shell "appops query-op $1 ignore" \
| tr -d '\r' \
| sort \
| sed -e 's/^/\t- /'

echo 'Deny:'
adb shell "appops query-op $1 deny" \
| tr -d '\r' \
| sort \
| sed -e 's/^/\t- /'

echo 'Default:'
adb shell "appops query-op $1 default" \
| tr -d '\r' \
| sort \
| sed -e 's/^/\t- /'
