#! /usr/bin/env bash

# Copyright © 2025, 2026 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

if
	(( 4 == BASH_VERSINFO[0] && 2 <= BASH_VERSINFO[1] \
	|| 4  < BASH_VERSINFO[0] \
	))
then
	unicode_feat='1'
else
	unicode_feat='0'
fi

if   (( 2 == $# ))
then
	diff --minimal "$@" \
	| grep -o '^[<>]' \
	| uniq \
	| sort \
	| uniq
elif (( 2 < $# ))
then
	source="${1}"
	shift
	for target in "$@"
	do
		if   [[ "${source}" != "${target}" ]]
		then
			op="$(
				diff --minimal "${source}" "${target}" \
				| grep -o '^[<>]' \
				| uniq \
				| sed -n -e 'H; ${ g; s/\n//g; p; }'
			)"
			case "${op}" in
				'<')
					plain_sign=' > '
					unicode_sign=$'\u2283'
					op_color=$'\e[32m'
				;;
				'>')
					plain_sign=' < '
					unicode_sign=$'\u2282'
					op_color=$'\e[33m'
				;;
				*)
					plain_sign='>/<'
					unicode_sign=$'\u2285'
					op_color=$'\e[31m'
			esac

			if   (( 0 < unicode_feat ))
			then
				if   (( 4 <= USER_COLORTERM ))
				then
					echo -e "${source} ${op_color}${unicode_sign}\e[0m ${target}"
				else
					echo "${source} ${unicode_sign} ${target}"
				fi
			else
				if   (( 4 <= USER_COLORTERM ))
				then
					echo -e "${source} ${op_color}${plain_sign}\e[0m ${target}"
				else
					echo "${source} ${plain_sign} ${target}"
				fi
			fi
		fi
	done
fi
