#! /usr/bin/env bash

# Copyright © 2025, 2026 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

blockdev=0
filesys=0

numbers=0
percents=0
units=0

header=0
box=0

show=0

sedfilter=''

for opt in "$@"
do
	case "${opt}" in
		--blockdev)
			if   (( blockdev < 1 ))
			then
				blockdev=1
				sedfilter="${sedfilter}"$'
s@(^|[[:space:]\u2500-\u257F])(/dev/[hsv]d[a-z][0-9]*)([[:space:]]|$)@\\1\e[93m\\2\e[39m\\3@g
s@(^|[[:space:]\u2500-\u257F])(/dev/sr[0-9]+)([[:space:]]|$)@\\1\e[93m\\2\e[39m\\3@g
s@(^|[[:space:]\u2500-\u257F])(/dev/nvme[0-9]+n[0-9]+p[0-9]+)([[:space:]]|$)@\\1\e[93m\\2\e[39m\\3@g
s@(^|[[:space:]\u2500-\u257F])(/dev/nvme[0-9]+n[0-9]+)([[:space:]]|$)@\\1\e[93m\\2\e[39m\\3@g
s@(^|[[:space:]\u2500-\u257F])(/dev/shm)([[:space:]]|$)@\\1\e[92m\\2\e[39m\\3@g
'
			fi
		;;
		--filesys)
			if   (( filesys < 1 ))
			then
				filesys=1
				sedfilter="${sedfilter}"$'
s/(^|[[:space:]])(bcachefs|btrfs|exfat|ext[234]|f2fs|hfsplusjfs|vfat|udf|xfs|zfs)([[:space:]]|$)/\\1\e[32m\\2\e[39m\\3/g
s/(^|[[:space:]])(tmpfs)([[:space:]]|$)/\\1\e[95m\\2\e[39m\\3/g
s/(^|[[:space:]])(ceph|cifs|coda|nfs)([[:space:]]|$)/\\1\e[96m\\2\e[39m\\3/g
s/(^|[[:space:]])(binfmt_misc|bpf|cgroup2|configfs|debugfs|devpts|devtmpfs|efivarfs|hugetlbfs|proc|securityfs|sysfs)([[:space:]]|$)/\\1\e[31m\\2\e[39m\\3/g
'
			fi
		;;
		--numbers)
			if   (( numbers < 1 ))
			then
				numbers=1
				sedfilter="${sedfilter}"$'
s/(^|[[:space:]])([-0])([[:space:]]|$)/\\1\e[90m\\2\e[39m\\3/g
s/(^|[[:space:]])([0-9]{1,3})([0-9]{3})([[:space:]]|$)/\\1\\2\e[90m\\3\e[39m\\4/g
s/(^|[[:space:]])([0-9]{1,3})([0-9]{3})([0-9]{3})([[:space:]]|$)/\\1\\2\e[90m\\3\e[39m\\4\\5/g
s/(^|[[:space:]])([0-9]{1,3})([0-9]{3})([0-9]{3})([0-9]{3})([[:space:]]|$)/\\1\\2\e[90m\\3\e[39m\\4\e[90m\\5\e[39m\\6/g
s/(^|[[:space:]])([0-9]{1,3})([0-9]{3})([0-9]{3})([0-9]{3})([0-9]{3})([[:space:]]|$)/\\1\\2\e[90m\\3\e[39m\\4\e[90m\\5\e[39m\\6\\7/g
'
			fi
		;;
		--percents)
			if   (( percents < 1 ))
			then
				percents=1
				sedfilter="${sedfilter}"$'
s/(^|[[:space:]])([9][0-9])%([[:space:]]|$)/\\1\e[31m\\2\e[39m%\\3/g
s/(^|[[:space:]])([8][0-9])%([[:space:]]|$)/\\1\e[33m\\2\e[39m%\\3/g
s/(^|[[:space:]])([2-7][0-9])%([[:space:]]|$)/\\1\e[32m\\2\e[39m%\\3/g
s/(^|[[:space:]])([10 ][0-9])%([[:space:]]|$)/\\1\e[35m\\2\e[39m%\\3/g
'
			fi
		;;
		--units)
			if   (( units < 1 ))
			then
				units=1
				sedfilter="${sedfilter}"$'
s/(^|[[:space:]])([0-9.]+)([KMGTPEZYRQ])(B|iB)?([[:space:]]|$)/\\1\\2\e[1;36m\\3\\4\e[22;39m\\5/g
s/(^|[[:space:]])([0-9.]+)([kmgtpezyrq])([[:space:]]|$)/\\1\\2\e[1;34m\\3\e[22;39m\\4/g
'
			fi
		;;
		--header)
			if   (( header < 1 ))
			then
				header=1
				sedfilter="${sedfilter}"$'
1s/^/\e[97;100m/
1s/$/\e[0m/
'
			fi
		;;
		--box)
			if   (( box < 1 ))
			then
				box=1
				sedfilter="${sedfilter}"$'
s/[\u2500-\u257F]/\e[36m&\e[39m/g
'
			fi
		;;
		--show)
			show=1
		;;
	esac
done

if   (( show < 1 ))
then
	sed -E -e "${sedfilter}" < /dev/stdin
else
	echo "${sedfilter}"
fi

