#! /usr/bin/env bash

# Copyright © 2025, 2026 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

# NOTE: filter-highlight requires bash 2.02

findmnt "$@" \
| filter-highlight --units --percents --blockdev --filesys --numbers --box
