#! /usr/bin/env bash

# Copyright © 2021, 2022, 2023, 2024, 2026 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

function usage()
{
echo '
usage: git clone-bare <remote-repository> [local-reference-repository]
'
}


if   [[ -n "${TMPDIR:-}" && -d "${TMPDIR}" ]]
then
	workdir="${TMPDIR}"
elif [[ 'Linux' == "$(uname -s)" && -d '/tmp' ]]
then
	workdir='/tmp'
fi

if   [[ -n "${USER:-}" ]]
then
	prefix="${USER}"
elif [[ -n "${USERNAME:-}" ]]
then
	prefix="${USERNAME}"
elif type -fP 'whoami' > '/dev/null' 2>&1
then
	prefix="$(whoami)"
fi

if   [[ -n "${workdir:-}" && -n "${prefix:-}" ]]
then
	treedir="${workdir}/${prefix}-git-clone"
else
	echo -e '\e[1;31mERROR: Unable to find a temporary directory for the initial checkout\e[0m' > '/dev/stderr'
	exit 1
fi

case $# in
	1)
		gitdir="$(basename "${1##*[@/]gist.github.com[:/]}")"
		# shellcheck disable=SC2115
		git clone --no-checkout --separate-git-dir="${gitdir}" "${1}" "${treedir}/${gitdir}" \
		&& sed -i -e 's/bare = false/bare = true/' "${gitdir}/config" \
		&& rm -rf "${treedir}/${gitdir}"
	;;
	2)
		gitdir="$(basename "${1}")"
		# shellcheck disable=SC2115
		git clone --reference-if-able "${2}" --no-checkout --separate-git-dir="${gitdir}" "${1}" "${treedir}/${gitdir}" \
		&& sed -i -e 's/bare = false/bare = true/' "${gitdir}/config" \
		&& rm -rf "${treedir}/${gitdir}" \
		&& git --git-dir="${gitdir}" remote add upstream "$(git --git-dir="$2" config --get remote.origin.url)"
	;;
	*)
		usage
	;;
esac
