#! /usr/bin/env bash

# Copyright © 2025, 2026 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

for command in \
	ip \
	sed \
	wol \
;
do
	if   ! which "${command}" > /dev/null 2>&1
	then
		echo -e "\e[1;31mERROR: ${command} command is not available\e[0m" > /dev/stderr
		exit 1
	fi
done

bcast=$(ip addr show "$1" | sed -ne '/inet /{s/.*brd //; s/ scope.*//; p}')

if   [[ -n "${bcast}" ]]
then
	shift
	if   (( 1 < $# ))
	then
		wol -v -w 3000 -i "${bcast}" "$@"
	else
		wol -v -i "${bcast}" "$@"
	fi
fi
