#! /usr/bin/env bash

# Copyright © 2025, 2026 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

zypper -s 1 --no-refresh search \
	"$@" \
| sed -E -e $'
	s/^Loading repository data...$/\e[34m&\e[0m/
	s/^Reading installed packages...$/\e[34m&\e[0m/

	s/([|:\u2502\u2503\u2506\u2507\u2551] )(package|patch|pattern|product|srcpackage)([[:space:]]+[|:\u2502\u2503\u2506\u2507\u2551] )([^- ]+)(-?)([^ ]*)/\\1\\2\\3\e[32m\\4\e[39m\\5\e[36m\\6\e[39m/

	/^   [|:\u2502\u2503\u2506\u2507\u2551]/{
		s/^  /\e[2m&/
		s/[|:\u2502\u2503\u2506\u2507\u2551]/\e[22m&\e[2m/g
	}

	/^i+ [|:\u2502\u2503\u2506\u2507\u2551]/{
		s/^i+/\e[1m&/
		s/[|:\u2502\u2503\u2506\u2507\u2551]/\e[22m&\e[1m/g
	}

	/^.l [|:\u2502\u2503\u2506\u2507\u2551]/{
		s/^.l/\e[31m&/
		s/[|:\u2502\u2503\u2506\u2507\u2551]/\e[0m&\e[31m/g
	}

	s/ srcpackage$/\e[90m&/

	s/ pattern$/\e[95m&/

	s/$/\e[0m/
' \
| less -SF
